name: 02 - Workflow Events

on:
  push:
    branches:
      - main

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Show the trigger
        run: echo "The workflow was triggered by ${{ github.event_name }}"
