name: 03 - Workflow Runners

on:
  workflow_dispatch:

jobs:
  windows-echo:
    runs-on: windows-latest
    steps:
      - name: Show OS
        run: |
          echo "The workflow is running on ${{ runner.os }}"

  macos-echo:
    runs-on: macos-latest
    steps:
      - name: Show OS
        run: |
          echo "The workflow is running on ${{ runner.os }}"
